from pathlib import Path
from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)


def generate_pdf(
    title,
    executive_summary,
    key_findings,
    recommendations,
):
    reports_dir = Path(__file__).parent / "reports"
    reports_dir.mkdir(exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = reports_dir / f"sales_report_{timestamp}.pdf"

    doc = SimpleDocTemplate(str(filename))
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(title, styles["Title"]))
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now().strftime('%B %d, %Y %H:%M')}",
            styles["Normal"],
        )
    )

    story.append(
        Paragraph(
            "<b>Prepared By:</b> Enterprise AI Platform",
            styles["Normal"],
        )
    )

    story.append(Spacer(1, 25))

    story.append(Paragraph("<b>Executive Summary</b>", styles["Heading1"]))
    story.append(Paragraph(executive_summary, styles["BodyText"]))

    story.append(Spacer(1, 15))

    story.append(Paragraph("<b>Key Findings</b>", styles["Heading1"]))
    story.append(Paragraph(key_findings, styles["BodyText"]))

    story.append(Spacer(1, 15))

    story.append(Paragraph("<b>Recommendations</b>", styles["Heading1"]))
    story.append(Paragraph(recommendations, styles["BodyText"]))

    story.append(Spacer(1, 25))

    story.append(
        Paragraph(
            "<font size='9'>Confidential – Generated by Enterprise AI Platform</font>",
            styles["Italic"],
        )
    )

    doc.build(story)

    return {
        "success": True,
        "file_path": str(filename),
        "generated_at": timestamp,
    }


if __name__ == "__main__":
    result = generate_pdf(
        title="Enterprise Sales Analytics Report",
        executive_summary=(
            "The West region generated the highest revenue during the reporting period. "
            "Overall sales performance remained strong across all regions."
        ),
        key_findings=(
            "West achieved the highest revenue.<br/>"
            "Southwest ranked second.<br/>"
            "South produced the lowest revenue."
        ),
        recommendations=(
            "Increase investment in high-performing regions while reviewing "
            "sales strategies in lower-performing regions."
        ),
    )

    print(result)